# Generated by Django 6.0.5 on 2026-05-14 18:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CIN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cin_number', models.CharField(max_length=12, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('recto_scan', models.TextField()),
                ('verso_scan', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('VALIDATED', 'Validé'), ('REVISION', 'À modifier')], default='PENDING', max_length=20)),
                ('revision_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
