# Generated by Django 6.0.5 on 2026-05-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cin',
            old_name='revision_notes',
            new_name='revision_note',
        ),
        migrations.RemoveField(
            model_name='cin',
            name='validated_at',
        ),
        migrations.AddField(
            model_name='cin',
            name='photo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
